use_frameworks!

platform :ios, '9.0'

target 'YDCollectionViewLayout_Example' do
  pod 'YDCollectionViewLayout', :path => '../'

  target 'YDCollectionViewLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
