source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'git@gitlab.miliantech.com:miliantech-ios/Specs.git'


platform :ios, '10.0'

use_frameworks!

target 'YDCollectionViewLayout_Example' do
  pod 'YDCollectionViewLayout', :path => '../'
end
